-- This SQL query calculates the total revenue generated by each customer based on their order details.
SELECT o.CustomerID, SUM(od.UnitPrice * od.Quantity) AS TotalRevenue
FROM Orders o
JOIN "Order Details" od ON o.OrderID = od.OrderID
GROUP BY o.CustomerID;

-- This SQL query retrieves the top 5 products with the highest unit price from the Products table.
SELECT product.ProductID, product.ProductName, product.UnitPrice
FROM Products product
ORDER BY product.UnitPrice DESC -- Orders the results by UnitPrice in descending order to get the highest priced products first.
LIMIT 5; -- Limits the results to the top 5 products with the highest unit price.