-- This SQL query calculates the total revenue generated by each customer based on their order details.
SELECT [order].CustomerID, SUM(orderDetails.UnitPrice * orderDetails.Quantity) AS TotalRevenue
FROM Orders [order]
JOIN "Order Details" orderDetails ON [order].OrderID = orderDetails.OrderID
GROUP BY [order].CustomerID;
-- order is a reversed keyword in SQL, so it is enclosed in square brackets to avoid syntax errors.

-- This SQL query retrieves the top 5 products with the highest unit price from the Products table.
SELECT product.ProductID, product.ProductName, product.UnitPrice
FROM Products product
ORDER BY product.UnitPrice DESC -- Orders the results by UnitPrice in descending order to get the highest priced products first.
LIMIT 5; -- Limits the results to the top 5 products with the highest unit price.